apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    cluster.x-k8s.io/aggregate-to-manager: "true"
    cluster.x-k8s.io/provider: cluster-api
  name: mce-labeling-role
rules:
- apiGroups:
  - ""
  resources:
  - namespaces
  verbs:
  - get
