apiVersion: v1
kind: Service
metadata:
  labels:
    app: mce-capi-webhook-config
  name: mce-capi-webhook-config-service
  namespace: capi-system
spec:
  ports:
  - port: 9443
    targetPort: 9443
  selector:
    app: mce-capi-webhook-config
