apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: capi1-system
configurations:
- namingConfiguration.yaml

## condsidering resources under cluster-api/config/default directory to generate the CAPI CRDs and CRs
resources:
- ../../charts/cluster-api/crds/apiextensions.k8s.io_v1_customresourcedefinition_clusterclasses.cluster.x-k8s.io.yaml
- ../../charts/cluster-api/crds/apiextensions.k8s.io_v1_customresourcedefinition_clusterresourcesetbindings.addons.cluster.x-k8s.io.yaml
- ../../charts/cluster-api/crds/apiextensions.k8s.io_v1_customresourcedefinition_clusterresourcesets.addons.cluster.x-k8s.io.yaml
- ../../charts/cluster-api/crds/apiextensions.k8s.io_v1_customresourcedefinition_clusters.cluster.x-k8s.io.yaml
- ../../charts/cluster-api/crds/apiextensions.k8s.io_v1_customresourcedefinition_extensionconfigs.runtime.cluster.x-k8s.io.yaml
- ../../charts/cluster-api/crds/apiextensions.k8s.io_v1_customresourcedefinition_machinedeployments.cluster.x-k8s.io.yaml
- ../../charts/cluster-api/crds/apiextensions.k8s.io_v1_customresourcedefinition_machinehealthchecks.cluster.x-k8s.io.yaml
- ../../charts/cluster-api/crds/apiextensions.k8s.io_v1_customresourcedefinition_machinepools.cluster.x-k8s.io.yaml
- ../../charts/cluster-api/crds/apiextensions.k8s.io_v1_customresourcedefinition_machines.cluster.x-k8s.io.yaml
- ../../charts/cluster-api/crds/apiextensions.k8s.io_v1_customresourcedefinition_machinesets.cluster.x-k8s.io.yaml
- ../../charts/cluster-api/templates/admissionregistration.k8s.io_v1_mutatingwebhookconfiguration_capi-mutating-webhook-configuration.yaml
- ../../charts/cluster-api/templates/admissionregistration.k8s.io_v1_validatingwebhookconfiguration_capi-validating-webhook-configuration.yaml
- ../../charts/cluster-api/templates/apps_v1_deployment_capi-controller-manager.yaml
- ../../charts/cluster-api/templates/rbac.authorization.k8s.io_v1_clusterrolebinding_capi-manager-rolebinding.yaml
- ../../charts/cluster-api/templates/rbac.authorization.k8s.io_v1_clusterrole_capi-aggregated-manager-role.yaml
- ../../charts/cluster-api/templates/rbac.authorization.k8s.io_v1_clusterrole_capi-manager-role.yaml
- ../../charts/cluster-api/templates/rbac.authorization.k8s.io_v1_rolebinding_capi-leader-election-rolebinding.yaml
- ../../charts/cluster-api/templates/rbac.authorization.k8s.io_v1_role_capi-leader-election-role.yaml
- ../../charts/cluster-api/templates/v1_namespace_capi-system.yaml
- ../../charts/cluster-api/templates/v1_serviceaccount_capi-manager.yaml
- ../../charts/cluster-api/templates/v1_service_capi-webhook-service.yaml

patches:
- patch: |-
    - op: add
      path: /spec/template/spec/containers/0/args/0
      value: --namespace=rosa-mveber1-a
    - op: add
      path: /spec/template/spec/containers/0/args/0
      value: --namespace=rosa-mveber1-b
  target:
    kind: Deployment
    name: capi-controller-manager
- patch: |-
    - op: add
      path: /subjects/0
      value:
        kind: ServiceAccount
        name: capi-manager
        namespace: capi2-system
  target:
    kind: ClusterRoleBinding
    name: capi-manager-rolebinding
