apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: azureserviceoperator-serving-cert
  namespace: capz-system
spec:
  dnsNames:
  - azureserviceoperator-webhook-service.capz-system.svc
  - azureserviceoperator-webhook-service.capz-system.svc.cluster.local
  issuerRef:
    kind: Issuer
    name: azureserviceoperator-selfsigned-issuer
  secretName: webhook-server-cert
  subject:
    organizations:
    - azure
