apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  labels:
    cluster.x-k8s.io/provider: infrastructure-azure
  name: capz-serving-cert
  namespace: capz-system
spec:
  dnsNames:
  - capz-webhook-service.capz-system.svc
  - capz-webhook-service.capz-system.svc.cluster.local
  issuerRef:
    kind: Issuer
    name: capz-selfsigned-issuer
  secretName: capz-webhook-service-cert
