apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: azureserviceoperator-crd-manager-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: azureserviceoperator-crd-manager-role
subjects:
- kind: ServiceAccount
  name: azureserviceoperator-default
  namespace: capz-system
