apiVersion: v1
kind: Secret
metadata:
  name: aso-controller-settings
  namespace: capz-system
stringData:
  AZURE_AUTHORITY_HOST: ""
  AZURE_CLIENT_ID: ""
  AZURE_RESOURCE_MANAGER_AUDIENCE: ""
  AZURE_RESOURCE_MANAGER_ENDPOINT: ""
  AZURE_SUBSCRIPTION_ID: ""
  AZURE_SYNC_PERIOD: ""
  AZURE_TENANT_ID: ""
  AZURE_USER_AGENT_SUFFIX: cluster-api-provider-azure/main
type: Opaque
