apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

## condsidering resources under cluster-api-provider-aws/config/default directory to generate the CAPA CRDs and CRs
resources:
- default/

transformers:
- base/transformer.yaml

## Patch the default CAPA CRDs & CRs with OCP dwonstream CAPA requirements. 
patches:
  # Replace service account annotation with AWS IAM role helm chart value
  - target:
      version: v1
      kind: ServiceAccount
      name: capa-controller-manager
    patch: |-
      - op: replace
        path: /metadata/annotations
        value:
          iam.amazonaws.com/role: '{{ .Values.aws.iamRole }}'
  # Replace sceret with AWS credentials helm chart value
  - target:
      version: v1
      kind: Secret
    patch: |-
      - op: replace
        path: /data/credentials
        value: '{{ .Values.aws.encodedCredentials }}'
  # Replace Deployment with default values & helm chart value
  - target:
      version: v1
      kind: Deployment
      name: capa-controller-manager
    patch: |-
      - op: replace
        path: /spec/template/metadata/annotations/iam.amazonaws.com~1role
        value: '{{ .Values.aws.iamRole }}'
      - op: replace
        path: /spec/template/spec/affinity/nodeAffinity/preferredDuringSchedulingIgnoredDuringExecution/0/preference/matchExpressions/0/key
        value: 'node-role.kubernetes.io/control-plane'
      - op: replace
        path: /spec/template/spec/containers/0/image
        value: '{{ .Values.manager.image.url  }}:{{ .Values.manager.image.tag  }}'
      - op: replace
        path: /spec/template/spec/containers/0/command
        value:
        - '{{ .Values.manager.cmd  }}'
      - op: add
        path: /spec/template/spec/containers/0/env
        value:
        - name: AWS_SHARED_CREDENTIALS_FILE
          value: /home/.aws/credentials
        - name: OCM_TOKEN
          value: '{{ .Values.rosa.ocmToken  }}'
      - op: replace
        path: /spec/template/spec/containers/0/imagePullPolicy
        value: IfNotPresent
