aws:
  encodedCredentials: ""
  iamRole: ""
rosa:
  ocmToken: ""
manager:
  cmd: /manager
  image:
    tag: nightly_main_20250122
    url: gcr.io/k8s-staging-cluster-api-aws/cluster-api-aws-controller
