manager:
  cmd: /manager
  image:
    tag: v1.11.0-alpha.2
    url: gcr.io/k8s-staging-cluster-api/cluster-api-controller
webhook:
  image:
    tag: latest
    url: quay.io/mveber/mce-capi-webhook-config
