---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: capi-admin-rolebinding
  labels:
    cluster.x-k8s.io/provider: cluster-api
roleRef:
  name: cluster-admin
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
subjects:
  - name: capi-manager
    kind: ServiceAccount
    namespace: capi-system

