name: Makefile CI

on:
  schedule:
    - cron: "10 15 * * *"

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Run sync
      run: make build-helm-charts
